---
engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.js"
  - "**.jsx"
  - "**.css"
exclude_paths:
- config/**/*
- test/**/*
- vendor/**/*
- tmp/**/*
